[package]
name = "mega-runtime"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
mega-core.workspace = true
mega-memory.workspace = true
mega-store.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tempfile = "3"
